[theme]
base = "dark"
primaryColor = "#FF1F53"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#141414"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
